_wandb:
    value:
        cli_version: 0.19.11
        m:
            - "1": train/global_step
              "6":
                - 3
              "7": []
        python_version: 3.10.14
        t:
            "1":
                - 1
                - 5
                - 11
                - 15
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
                - 105
            "2":
                - 1
                - 5
                - 11
                - 15
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
                - 105
            "3":
                - 7
                - 13
                - 23
                - 55
                - 66
            "4": 3.10.14
            "5": 0.19.11
            "6": 4.39.3
            "8":
                - 5
            "9":
                "1": transformers_trainer
            "12": 0.19.11
            "13": darwin-arm64
accelerator_config:
    value:
        dispatch_batches: null
        even_batches: true
        split_batches: false
        use_seedable_sampler: true
adafactor:
    value: false
adam_beta1:
    value: 0.9
adam_beta2:
    value: 0.999
adam_epsilon:
    value: 1e-08
auto_find_batch_size:
    value: false
bf16:
    value: false
bf16_full_eval:
    value: false
data_seed:
    value: null
dataloader_drop_last:
    value: false
dataloader_num_workers:
    value: 4
dataloader_persistent_workers:
    value: false
dataloader_pin_memory:
    value: true
dataloader_prefetch_factor:
    value: null
ddp_backend:
    value: null
ddp_broadcast_buffers:
    value: null
ddp_bucket_cap_mb:
    value: null
ddp_find_unused_parameters:
    value: null
ddp_timeout:
    value: 1800
debug:
    value: []
deepspeed:
    value: null
disable_tqdm:
    value: false
dispatch_batches:
    value: null
do_eval:
    value: false
do_predict:
    value: false
do_train:
    value: false
eval_accumulation_steps:
    value: null
eval_delay:
    value: 0
eval_steps:
    value: 1000
evaluation_strategy:
    value: "no"
fp16:
    value: false
fp16_backend:
    value: auto
fp16_full_eval:
    value: false
fp16_opt_level:
    value: O1
fsdp:
    value: []
fsdp_config:
    value:
        min_num_params: 0
        xla: false
        xla_fsdp_grad_ckpt: false
        xla_fsdp_v2: false
fsdp_min_num_params:
    value: 0
fsdp_transformer_layer_cls_to_wrap:
    value: null
full_determinism:
    value: false
gradient_accumulation_steps:
    value: 4
gradient_checkpointing:
    value: false
gradient_checkpointing_kwargs:
    value: null
greater_is_better:
    value: true
group_by_length:
    value: false
half_precision_backend:
    value: auto
hub_always_push:
    value: false
hub_model_id:
    value: null
hub_private_repo:
    value: false
hub_strategy:
    value: every_save
hub_token:
    value: <HUB_TOKEN>
ignore_data_skip:
    value: false
include_inputs_for_metrics:
    value: false
include_num_input_tokens_seen:
    value: false
include_tokens_per_second:
    value: false
jit_mode_eval:
    value: false
label_names:
    value: null
label_smoothing_factor:
    value: 0
learning_rate:
    value: 5e-05
length_column_name:
    value: length
load_best_model_at_end:
    value: false
local_rank:
    value: 0
log_level:
    value: passive
log_level_replica:
    value: warning
log_on_each_node:
    value: true
logging_dir:
    value: ./model/baseline/runs/May13_16-54-49_gangminguui-MacBookPro.local
logging_first_step:
    value: false
logging_nan_inf_filter:
    value: true
logging_steps:
    value: 10
logging_strategy:
    value: steps
lr_scheduler_type:
    value: linear
max_grad_norm:
    value: 1
max_steps:
    value: -1
metric_for_best_model:
    value: f1_score
mp_parameters:
    value: ""
neftune_noise_alpha:
    value: null
no_cuda:
    value: false
num_train_epochs:
    value: 10
optim:
    value: adamw_torch
optim_args:
    value: null
optim_target_modules:
    value: null
output_dir:
    value: ./model/baseline
overwrite_output_dir:
    value: false
past_index:
    value: -1
per_device_eval_batch_size:
    value: 1
per_device_train_batch_size:
    value: 1
per_gpu_eval_batch_size:
    value: null
per_gpu_train_batch_size:
    value: null
prediction_loss_only:
    value: false
push_to_hub:
    value: false
push_to_hub_model_id:
    value: null
push_to_hub_organization:
    value: null
push_to_hub_token:
    value: <PUSH_TO_HUB_TOKEN>
ray_scope:
    value: last
remove_unused_columns:
    value: false
report_to:
    value:
        - wandb
resume_from_checkpoint:
    value: null
run_name:
    value: ./model/baseline
save_on_each_node:
    value: false
save_only_model:
    value: false
save_safetensors:
    value: true
save_steps:
    value: 1000
save_strategy:
    value: steps
save_total_limit:
    value: null
seed:
    value: 42
skip_memory_metrics:
    value: true
split_batches:
    value: null
tf32:
    value: null
torch_compile:
    value: false
torch_compile_backend:
    value: null
torch_compile_mode:
    value: null
torchdynamo:
    value: null
tpu_metrics_debug:
    value: false
tpu_num_cores:
    value: null
use_cpu:
    value: false
use_ipex:
    value: false
use_legacy_prediction_loop:
    value: false
use_mps_device:
    value: false
warmup_ratio:
    value: 0.1
warmup_steps:
    value: 0
weight_decay:
    value: 0
